service: scores-service-fanout
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  environment:
    GRIP_URL: https://api.fanout.io/realm/c2f47682?iss=c2f47682&key=base64:JciP77y/AekMKyeoLl452A==
  role: arn:aws:iam::329054710135:role/lambda-kinesis-ants

functions:
  serveEvents:
    handler: handler.handler

    events:
      - http:
          path: ''
          method: get
          cors: true

  publishPlayerScoreEventsHandler:
    handler: handler.publishPlayerScoreEventsHandler

    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:us-west-2:329054710135:table/Ants-Smashing-PlayersScore/stream/2018-02-21T21:40:38.366

#  publishTeamScoreEventsHandler:
#    handler: handler.publishTeamScoreEventsHandler
#
#    events:
#      - stream:
#          type: dynamodb
#          arn: arn:aws:dynamodb:us-west-2:329054710135:table/Ants-Smashing-TeamsScore/stream/2018-02-21T21:40:39.849

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "fuze.tikal.io"
    basePath: 'events'
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional'
